#include "gateway/webui_display.h"

#include <string.h>

/* Minified single-file WebUI: zero dependencies, vanilla JS */
static const char *s_html =
    "<!DOCTYPE html><html lang=\"zh-CN\"><head><meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
    "<title>MimiClaw Display</title>"
    "<style>"
    "body{font-family:system-ui,-apple-system,sans-serif;max-width:480px;margin:0 auto;padding:16px;background:#f5f5f5}"
    ".card{background:#fff;border-radius:8px;padding:16px;margin-bottom:12px;box-shadow:0 1px 3px rgba(0,0,0,.1)}"
    "h1{font-size:20px;margin:0 0 12px}"
    "h2{font-size:16px;margin:0 0 10px;color:#333}"
    "input,textarea{width:100%;padding:8px;border:1px solid #ddd;border-radius:4px;box-sizing:border-box;margin-bottom:8px;font-size:14px}"
    "textarea{resize:vertical;min-height:48px}"
    "button{background:#007aff;color:#fff;border:none;padding:8px 16px;border-radius:4px;cursor:pointer;font-size:14px;margin-right:6px}"
    "button:hover{background:#0056d6}button:disabled{background:#ccc}"
    ".status{font-size:12px;color:#666;margin-bottom:12px}"
    ".status.ok{color:#28a745}.status.err{color:#dc3545}"
    ".todo-row{display:flex;gap:8px;margin-bottom:6px}"
    ".todo-row input{flex:1;margin-bottom:0}"
    ".todo-row button{background:#dc3545;padding:4px 10px;font-size:12px}"
    "#state{white-space:pre-wrap;font-size:12px;background:#f8f9fa;padding:10px;border-radius:4px;max-height:250px;overflow:auto}"
    "</style></head><body>"
    "<h1>MimiClaw 墨水屏控制</h1>"
    "<div class=\"status\" id=\"conn\">连接中...</div>"
    "<div class=\"card\">"
    "<div style=\"display:flex;gap:8px;margin-bottom:10px\">"
    "<button onclick=\"getState()\">获取状态</button>"
    "<button onclick=\"refresh()\">刷新屏幕</button></div>"
    "<h2>当前状态</h2><div id=\"state\">等待连接...</div></div>"
    "<div class=\"card\"><h2>天气</h2>"
    "<input id=\"city\" placeholder=\"城市\">"
    "<input id=\"summary\" placeholder=\"天气摘要\">"
    "<button onclick=\"setWeather()\">更新天气</button></div>"
    "<div class=\"card\"><h2>待办事项</h2><div id=\"todos\"></div>"
    "<button onclick=\"addTodo()\">添加待办</button>"
    "<button onclick=\"setTodos()\">更新待办</button></div>"
    "<div class=\"card\"><h2>每日金句</h2>"
    "<textarea id=\"quote\" placeholder=\"金句内容\"></textarea>"
    "<button onclick=\"setQuote()\">更新金句</button></div>"
    "<script>"
    "let ws;const $=id=>document.getElementById(id);"
    "function connect(){"
    "ws=new WebSocket('ws://'+location.host+':18789/');"
    "ws.onopen=()=>{$('conn').textContent='已连接';$('conn').className='status ok';getState();};"
    "ws.onclose=()=>{$('conn').textContent='已断开，5秒后重连...';$('conn').className='status err';setTimeout(connect,5000);};"
    "ws.onerror=()=>{$('conn').textContent='连接错误';$('conn').className='status err';};"
    "ws.onmessage=e=>{"
    "const d=JSON.parse(e.data);"
    "if(d.type==='display_state'){"
    "$('state').textContent=JSON.stringify(d.state,null,2);"
    "if(d.state){"
    "$('city').value=d.state.weather_city||'';"
    "$('summary').value=d.state.weather_summary||'';"
    "$('quote').value=d.state.quote||'';"
    "renderTodos(d.state.todos||[]);"
    "}"
    "}else if(d.type==='display_ack'){"
    "if(d.status!=='ok')alert(d.action+' 失败: '+(d.message||''));"
    "else if(d.action!=='refresh')getState();"
    "}"
    "};}"
    "function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o));}"
    "function getState(){send({type:'display',action:'get_state'});}"
    "function refresh(){send({type:'display',action:'refresh'});}"
    "function setWeather(){send({type:'display',action:'set_weather',city:$('city').value,summary:$('summary').value});}"
    "function renderTodos(list){$('todos').innerHTML='';list.forEach(t=>addTodo(t));}"
    "function addTodo(v){const r=document.createElement('div');r.className='todo-row';"
    "r.innerHTML='<input value=\"'+(v||'')+'\" placeholder=\"待办内容\"><button onclick=\"this.parentNode.remove()\">删除</button>';"
    "$('todos').appendChild(r);}"
    "function setTodos(){const a=[];$('todos').querySelectorAll('input').forEach(i=>{if(i.value.trim())a.push(i.value.trim())});"
    "send({type:'display',action:'set_todos',todos:a});}"
    "function setQuote(){send({type:'display',action:'set_quote',quote:$('quote').value});}"
    "connect();"
    "</script></body></html>";

esp_err_t webui_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    return httpd_resp_send(req, s_html, strlen(s_html));
}
